Początek programu **tekst pogrubiony**\
Nowa linia

# Nowa sekcja
## Nowa sekcje
### Nowa sekcja

In [1]:
print("Radek")

Radek


In [2]:
a = 5
b = 5
print(a, b)

5 5


In [3]:
a

5

In [4]:
print(c)

NameError: name 'c' is not defined

# Biblioteka NumPy

Napisana w C, do szybkich operacji na danych tablicowych\
Podstawowy element: ndarray

In [5]:
!pip list

Package                   Version
------------------------- -----------
anyio                     4.11.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.0.5
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.2
bleach                    6.3.0
certifi                   2025.11.12
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.17
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.1.0
ipython                   9.7.0
ipython_pygments_lexers   1.1.1
isoduration       

In [6]:
!pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------  12.8/12.9 MB 96.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 68.8 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

In [8]:
lista = [2, 4, 6, 8, 10]
lista

[2, 4, 6, 8, 10]

In [9]:
a = np.array(lista)
a

array([ 2,  4,  6,  8, 10])

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print(a.dtype)

int64


int64 - 8 bajtów

In [12]:
print(a.shape)  # kształt tablicy

(5,)


In [13]:
p = np.zeros((3, 3))  # tablica z zerami
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
print(p.dtype)

float64


float64 - 8 bitów

In [15]:
q = np.ones((2, 2))  # tablica jedynek
q

array([[1., 1.],
       [1., 1.]])

In [16]:
q.dtype

dtype('float64')

In [17]:
s = np.eye(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
s.dtype

dtype('float64')

In [19]:
t = np.random.random((3, 3))
t

array([[0.7091126 , 0.28964116, 0.96786806],
       [0.49894234, 0.93731917, 0.60293689],
       [0.2718629 , 0.40609281, 0.28967237]])

In [20]:
t.dtype

dtype('float64')

In [21]:
r = np.full((2, 2), 4)
r

array([[4, 4],
       [4, 4]])

In [22]:
lista2 = [[5, 6], [7, 8]]
lista2

[[5, 6], [7, 8]]

In [23]:
b = np.array(lista2)
b

array([[5, 6],
       [7, 8]])

In [24]:
print(b)

[[5 6]
 [7 8]]


In [26]:
b.shape

(2, 2)

ravel() - spłaszczenie, zwraca nowy obiekt

In [27]:
print(b.ravel())

[5 6 7 8]


In [28]:
print(b[0])

[5 6]


In [29]:
print(b[0, 0])
print(b[0, 1])

5
6


In [30]:
print(np.float64(21))

21.0


In [31]:
print(np.int64(22.0))

22


In [32]:
print(np.bool(21))

True


In [33]:
print(np.float64(True))

1.0


In [34]:
arr = np.arange(1, 11, dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [36]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
arr.dtype

dtype('float64')

In [40]:
arr = np.arange(12)

In [41]:
arr.shape

(12,)

reshape() - zmiana kształtu

In [42]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
new_arr = arr.reshape(3, 4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
new_arr = arr.reshape(3, 5)  # nie zgada się kształt

ValueError: cannot reshape array of size 12 into shape (3,5)

In [45]:
new_arr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

ravel() - zwraca widok\
operacje na widoku "tablicy" wpływaja na zmainy oryginalnej tablicy

In [46]:
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten() - robi kopię\
zmiany nie wpływają na oryginlaną tablicę

In [47]:
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [48]:
flat = new_arr.flatten()  # kopia
rav = new_arr.ravel()  # widok

In [49]:
flat[0] = 999  # kopia, nie zmienia oryginału
rav[1] = 888  # widok, wpływa na oryginał

In [50]:
print(new_arr)

[[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


transspose() - zamienia osie

In [51]:
print(new_arr.transpose())

[[  0   4   8]
 [888   5   9]
 [  2   6  10]
 [  3   7  11]]


resize() - zmienia rozmiar tablicy\
zmienia oryginalna tablice (in-place)\
brakujące elementy uzupełni zerami

In [52]:
new_arr.resize(1, 12)
new_arr

array([[  0, 888,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11]])

In [53]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
print(np.__version__)

2.3.5


### Broadcasting
Wykonuje operacje na wszystkich elementach tablicy

### Zasady bradcastingu
wymiary muszą być zgodne
1. Dwa wymiary są zgodne jeśli są równe, lub jeden z nich ma rozmiar 1
2. Jeśli nie spełniają tych warunków -> ValueError

In [55]:
lista = [1, 2, 3]
print(2 * lista)

[1, 2, 3, 1, 2, 3]


In [56]:
arr2 = 2 * arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [58]:
arrx = arr1 + arr2
arrx

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

hstack() - skleja tablice poziomo

In [59]:
arr3 = np.hstack((arr1, arr2))
arr3

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [60]:
print(arr3)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


vstack() - skleja pionowo

In [61]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


concatenate() - skleja w wybranej osi

In [63]:
arr5 = np.concatenate((arr1, arr2), axis=0)  # wiersze
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [64]:
arr6 = np.concatenate((arr1, arr2), axis=1)  # kolumny
arr6

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

Tworzy tablicę z sekwencji

In [65]:
arre1 = np.array([1, 2, 3])
print(arre1)

[1 2 3]


In [66]:
arre2 = np.array([4, 5, 6])
print(arre2)

[4 5 6]


In [68]:
np.concatenate((arre1, arre2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [69]:
np.concatenate((arre1, arre2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [72]:
print(arre1)
arre1.shape

[1 2 3]


(3,)

In [74]:
print(arre2)
arre2.shape

[4 5 6]


(3,)

dstack() - skleja tablice w głab, dodaje trzeci wymiar

In [76]:
arr7 = np.dstack((arr1, arr2))
arr7

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

In [77]:
print(arr7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


column_stack() - skleja jako kolumny

In [78]:
arr8 = np.arange(4, 7)
print(arr8)
arr9 = 2 * arr8
print(arr9)

arr_col_stack = np.column_stack((arr8, arr9))
print(arr_col_stack)

[4 5 6]
[ 8 10 12]
[[ 4  8]
 [ 5 10]
 [ 6 12]]


row_stack() - jako wiersze

In [79]:
arr_row_stack = np.row_stack((arr8, arr9))
arr_row_stack

C:\Users\CSComarch\AppData\Local\Temp\ipykernel_14436\2835450636.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr_row_stack = np.row_stack((arr8, arr9))


array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [80]:
result_vstack = np.vstack((arr8, arr9))
result_vstack

array([[ 4,  5,  6],
       [ 8, 10, 12]])

hsplit() - dzieli w poziomie

In [81]:
arr10 = np.arange(1, 10).reshape(3, 3)
print(arr10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
arr_split = np.hsplit(arr10, 3)
print(arr_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


vsplit() - dzieli na wiersze

In [84]:
arr_v_split = np.vsplit(arr10, 3)
arr_v_split

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [85]:
arr11 = np.arange(1, 10).reshape(3, 3)
print("Tablica w typie integer:", arr11.dtype)

Tablica w typie integer: int64


In [86]:
# konwersja tablicy na inny typ
# tworzy nową tablicę
arr12 = arr11.astype(float)
print("Zmieniony typ na:", arr12.dtype)

Zmieniony typ na: float64


In [87]:
# zamiana na typy pythonowe
list1 = arr1.tolist()
print("Lista pythonowa:", list1)
print("Typ listy:", type(list1))

Lista pythonowa: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Typ listy: <class 'list'>


In [88]:
arr13 = np.arange(1, 5).reshape(2, 2)
arr13

array([[1, 2],
       [3, 4]])

In [89]:
arr_copy = arr13.copy()
arr_view = arr13.view()
arr_no_copy = arr13

In [90]:
print("Pierwotna tablica", id(arr13))
print("Kopia głęboka", id(arr_copy))
print("Kopia płytka (widok)", id(arr_view))
print("Referencja", id(arr_no_copy))

Pierwotna tablica 1775718273104
Kopia głęboka 1775718274256
Kopia płytka (widok) 1775718273776
Referencja 1775718273104


In [91]:
arr13[1] = [99, 100]

In [92]:
print('Widok:', arr_view)
print("Kopia:", arr_copy)

Widok: [[  1   2]
 [ 99 100]]
Kopia: [[1 2]
 [3 4]]


In [2]:
import numpy as np

In [3]:
arr14 = np.arange(0, 10)
print(arr14)
print(arr14[3:6])  # z prawej otwarty

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]


In [4]:
print(arr14[2:7:3])

[2 5]


filtrowanie danych

In [5]:
arr15 = np.arange(21, 41, 2)
arr15

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [6]:
print(arr15[arr15 > 30])  # filtrowanie danych

[31 33 35 37 39]


wczytanie csv

In [7]:
input_stock_price_array = np.genfromtxt('AAPL_stock_price_example.csv',
                                        delimiter=",", names=True, usecols=(1))
# usecols() - wybrane kolumny

In [8]:
print(input_stock_price_array.size)

229


In [9]:
input_stock_price_array = np.genfromtxt('data/AAPL_stock_price_example.csv',
                                        delimiter=",", names=True, usecols=(1))

In [10]:
print(input_stock_price_array.size)

229


In [11]:
temp_array = []
with open('data/AAPL_stock_price_example.csv', "r") as input_file:
    all_lines = input_file.readlines()
    for each_line in all_lines:
        for value_from_line in each_line.rsplit(",")[1:]:
            clean_value = value_from_line.replace("\n", "")
            temp_array.append(clean_value)

In [12]:
print(temp_array[:5])

['Close', '157.919998', '142.190002', '148.259995', '147.929993']


In [13]:
print(len(temp_array))

230


In [14]:
temp_array = np.delete(temp_array, 0)  # usunięcie pierwszego wiersza z nazwami kolumn

In [15]:
temp_array.size

229

In [16]:
temp_array.dtype

dtype('<U10')

typ tekstowy, unicode, 10 znaków

zamienic typ na float

ctrl shift f - wyszukiwanie w kodzie

In [17]:
input_stock_price = temp_array.astype(float) # zamiana na float

In [19]:
print(input_stock_price[:5])

[157.919998 142.190002 148.259995 147.929993 150.75    ]


In [20]:
sortd_stock_price = np.sort(input_stock_price)[::-1]
sortd_stock_price[0]

np.float64(267.100006)

https://www.kaggle.com/datasets