Początek programu **tekst pogrubiony**\
Nowa linia

# Nowa sekcja
## Nowa sekcje
### Nowa sekcja

In [1]:
print("Radek")

Radek


In [2]:
a = 5
b = 5
print(a, b)

5 5


In [3]:
a

5

In [4]:
print(c)

NameError: name 'c' is not defined

# Biblioteka NumPy

Napisana w C, do szybkich operacji na danych tablicowych\
Podstawowy element: ndarray

In [5]:
!pip list

Package                   Version
------------------------- -----------
anyio                     4.11.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.0.5
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.2
bleach                    6.3.0
certifi                   2025.11.12
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.17
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.1.0
ipython                   9.7.0
ipython_pygments_lexers   1.1.1
isoduration       

In [6]:
!pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------  12.8/12.9 MB 96.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 68.8 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

In [8]:
lista = [2, 4, 6, 8, 10]
lista

[2, 4, 6, 8, 10]

In [9]:
a = np.array(lista)
a

array([ 2,  4,  6,  8, 10])

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print(a.dtype)

int64


int64 - 8 bajtów

In [12]:
print(a.shape)  # kształt tablicy

(5,)


In [13]:
p = np.zeros((3, 3))  # tablica z zerami
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
print(p.dtype)

float64


float64 - 8 bitów

In [15]:
q = np.ones((2, 2))  # tablica jedynek
q

array([[1., 1.],
       [1., 1.]])

In [16]:
q.dtype

dtype('float64')

In [17]:
s = np.eye(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
s.dtype

dtype('float64')

In [19]:
t = np.random.random((3, 3))
t

array([[0.7091126 , 0.28964116, 0.96786806],
       [0.49894234, 0.93731917, 0.60293689],
       [0.2718629 , 0.40609281, 0.28967237]])

In [20]:
t.dtype

dtype('float64')

In [21]:
r = np.full((2, 2), 4)
r

array([[4, 4],
       [4, 4]])

In [22]:
lista2 = [[5, 6], [7, 8]]
lista2

[[5, 6], [7, 8]]

In [23]:
b = np.array(lista2)
b

array([[5, 6],
       [7, 8]])

In [24]:
print(b)

[[5 6]
 [7 8]]


In [26]:
b.shape

(2, 2)

ravel() - spłaszczenie, zwraca nowy obiekt

In [27]:
print(b.ravel())

[5 6 7 8]


In [28]:
print(b[0])

[5 6]


In [29]:
print(b[0, 0])
print(b[0, 1])

5
6


In [30]:
print(np.float64(21))

21.0


In [31]:
print(np.int64(22.0))

22


In [32]:
print(np.bool(21))

True


In [33]:
print(np.float64(True))

1.0


In [34]:
arr = np.arange(1, 11, dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [36]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
arr.dtype

dtype('float64')

In [40]:
arr = np.arange(12)

In [41]:
arr.shape

(12,)

reshape() - zmiana kształtu

In [42]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
new_arr = arr.reshape(3, 4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
new_arr = arr.reshape(3, 5)  # nie zgada się kształt

ValueError: cannot reshape array of size 12 into shape (3,5)

In [45]:
new_arr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

ravel() - zwraca widok\
operacje na widoku "tablicy" wpływaja na zmainy oryginalnej tablicy

In [46]:
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten() - robi kopię\
zmiany nie wpływają na oryginlaną tablicę

In [47]:
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [48]:
flat = new_arr.flatten()  # kopia
rav = new_arr.ravel()  # widok

In [49]:
flat[0] = 999  # kopia, nie zmienia oryginału
rav[1] = 888  # widok, wpływa na oryginał

In [50]:
print(new_arr)

[[  0 888   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
